name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "24.3.4"
          gleam-version: "0.21.0"
      - run: gleam format --check src test
      - run: gleam test --target erlang
      - run: gleam test --target javascript
